model_params:
  max_seq_len: 20
  h_dim: 64
  nhead : 2
  token_dim: 64
  nEncoders: 2
  dropout: 0.2
  k: [1, 5, 10, 50, 100]

data_params:
  data_path: "/media/media/pavans/spotify/training_set/"
  batch_size: 128
  patch_size: 64
  num_workers: 4


exp_params:
  lr: 0.001
  manual_seed: 1265

trainer_params:
  max_epochs: 25
  accelerator: "gpu"
  devices: [0]

logging_params:
  save_dir: "logger_runs/logsTransformer/"
  name: 'VanillaT'