model_params:
  max_seq_len: 20
  h_dim: 256
  nhead : 4
  token_dim: 256
  nEncoders: 2
  dropout: 0.2
  k: [1, 5, 10, 50, 100]

data_params:
  data_path: "/mnt/data2/pavans/pavans/training_set/"
  batch_size: 128
  patch_size: 64
  num_workers: 4


exp_params:
  lr: 0.0001
  manual_seed: 1265

trainer_params:
  max_epochs: 20
  accelerator: "gpu"
  devices: 1

logging_params:
  save_dir: "logger_runs/logsTransformer/"
  name: 'VanillaT'