model_params:
  max_seq_len: 20
  h_dim: 128
  nhead : 8
  token_dim: 128
  nEncoders: 2
  dropout: 0.2
  k: [1, 5, 10, 20, 50, 100]
  return_skip: True
  lr: 0.005
  bidirectional: True

dual_train: False
dev: False

data_params:
  data_path: "/media/pavans/spotify/training_set/"
  load_ckpt: False
  ckpt_path: "/home/pavans/dev/sequential-music-recommendation/logger_runs/newAuroc/VanillaTinitial 200 epoch run /version_0/checkpoints"
  ckpt_type: "/home/pavans/dev/sequential-music-recommendation/logger_runs/newAuroc/VanillaT: test checkpoint logic/version_2/checkpoints/epoch=0-step=1487.ckpt"
  batch_size: 128
  patch_size: 64
  num_workers: 4


exp_params:
  manual_seed: 1265

trainer_params:
  max_epochs: 40
  accelerator: "gpu"
  devices: [0]

logging_params:
  save_dir: "logger_runs/newAuroc/"
  name: 'VanillaT'