model_params:
  max_seq_len: 20
  h_dim: 128
  nhead : 8
  token_dim: 128
  nEncoders: 2
  dropout: 0.2
  k: [1, 5, 10, 20]
  return_skip: False
  lr: 0.005
  bidirectional: False
  wt: 0.25

dual_train: False
dev: False

data_params:
  data_path: "/home/pavans/dev/sequential-music-recommendation/datasets/lfm-2b/2012_subset/plays_with_session_with_skip_total_1.csv"
  load_ckpt: False
  ckpt_path: "/home/pavans/dev/sequential-music-recommendation/logger_runs/newAuroc/VanillaTinitial 200 epoch run /version_0/checkpoints"
  ckpt_type: "/home/pavans/dev/sequential-music-recommendation/logger_runs/LFM-2B/LFM-2B_2012-2014: skip/version_1/checkpoints/last.ckpt"
  batch_size: 32
  patch_size: 64
  num_workers: 4


exp_params:
  manual_seed: 1265

trainer_params:
  max_epochs: 20
  accelerator: "gpu"
  devices: [0]

logging_params:
  save_dir: "logger_runs/LFM-2B/"
  name: "LFM-2B_2012-2014"